### ISSUE TITLE
Explicit `model_parameters.lme()` and `ci.lme()` with df_method

### ISSUE THREAD

**Issue by Generalized** [easystats/parameters#198]
```
library(nlme)
library(parameters)
m <- lme(distance~age+Sex, random=~1|Subject, data=Orthodont, method="ML")
```
The default output  (fixed part):
```
Fixed effects: distance ~ age + Sex 
                Value Std.Error DF   t-value p-value
(Intercept) 17.706713 0.8315459 80 21.293729  0.0000
age          0.660185 0.0620929 80 10.632212  0.0000
SexFemale   -2.321023 0.7430668 25 -3.123572  0.0045
```
Now, when I request the output from _**parameters**_, I get the same DF for each term. 

```
> model_parameters(m, df_method = "wald")
Parameter    | Coefficient |   SE |         95% CI |     t |  df |      p
-------------------------------------------------------------------------
(Intercept)  |       17.71 | 0.83 | [16.08, 19.34] | 21.29 | 105 | < .001
age          |        0.66 | 0.06 | [ 0.54,  0.78] | 10.63 | 105 | < .001
Sex [Female] |       -2.32 | 0.74 | [-3.83, -0.81] | -3.12 | 105 | 0.004 
```

Moreover, it neither complains that I use incorrect option nor informs me what method was used actually:

```
> model_parameters(m, df_method = "kenward")  # no K-R for nlme in R (without LavaSearch2)

Parameter    | Coefficient |   SE |         95% CI |     t |  df |      p
-------------------------------------------------------------------------
(Intercept)  |       17.71 | 0.83 | [16.08, 19.34] | 21.29 | 105 | < .001
age          |        0.66 | 0.06 | [ 0.54,  0.78] | 10.63 | 105 | < .001
Sex [Female] |       -2.32 | 0.74 | [-3.83, -0.81] | -3.12 | 105 | 0.004 

> model_parameters(m, df_method = "abc")   # just anything
Parameter    | Coefficient |   SE |         95% CI |     t |  df |      p
-------------------------------------------------------------------------
(Intercept)  |       17.71 | 0.83 | [16.08, 19.34] | 21.29 | 105 | < .001
age          |        0.66 | 0.06 | [ 0.54,  0.78] | 10.63 | 105 | < .001
Sex [Female] |       -2.32 | 0.74 | [-3.83, -0.81] | -3.12 | 105 | 0.004 
```

OK, so we see it doesn't refuse to calculate K-R and reports just DF=105. So let's check the true K-R. I have to use the lavaSearch2 implementation for the nlme object:
```
library("lavaSearch2")   #version 1.5.4
sCorrect(m) <- TRUE

> summary2(m)$tTable
                 Value  Std.Error   t-value     p-value        df
(Intercept) 17.7067130 0.84095292 21.055534 0.000000000 104.15030
age          0.6601852 0.06239074 10.581462 0.000000000  82.87867
SexFemale   -2.3210227 0.76141684 -3.048294 0.005199027  26.25000
```

Let's compare this outcome with the pbkrtest (I refitted the model via lme4). We can see, that even if the lavaSearch2 version of the K-R slightly differs from pbkrtest, it's consistent
```
> m1 <- lme4::lmer(distance~age+Sex+(1|Subject), data=Orthodont, REML=FALSE)
> dof_kenward(m1)
(Intercept)         age   SexFemale 
  108.93636    82.01227    29.16026 
```

So it's definitely not DF=105. So, the correction doesn't work and the DFs still relate to Wald's (I guess). It looks, however, wrong, compared to the output of the nlme.

Session info:

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] parameters_0.4.1 nlme_3.1-143    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          magrittr_1.5        splines_3.6.2       MASS_7.3-51.4       tidyselect_0.2.5    insight_0.8.0       munsell_0.5.0       colorspace_1.4-1    lattice_0.20-38    
[10] R6_2.4.1            rlang_0.4.2         minqa_1.2.4         dplyr_0.8.3         tools_3.6.2         parallel_3.6.2      pbkrtest_0.4-7      grid_3.6.2          gtable_0.3.0       
[19] bayestestR_0.5.0    assertthat_0.2.1    lazyeval_0.2.2      lme4_1.1-21         tibble_2.1.3        lifecycle_0.1.0     numDeriv_2016.8-1.1 crayon_1.3.4        Matrix_1.2-18      
[28] purrr_0.3.3         nloptr_1.2.1        ggplot2_3.2.1       glue_1.3.1          pillar_1.4.3        compiler_3.6.2      scales_1.1.0        lmerTest_3.1-1      boot_1.3-23        
[37] pkgconfig_2.0.3    

```

**Comment by strengejacke** [comment]
Ok, the issue with the wrong DF has been fixed. However, nlme is not supported by pbkrtest, so I'm not sure whether KR-approximated DFs will be implemented for lme().

**Comment by strengejacke** [comment]
satterthwaite DF methods are now working with nlme. What I need to do now is to implement a specific `model_parameters.lme()` method, that also takes the `df_method()` argument into account, and a `ci.lme()` method that also accepts the `method`-argument.

**Comment by Generalized** [comment]
Thanks a lot! It was an immediate reaction!
Regarding the nlme, you don't need the pbkrtest. lavaSearch2 gives quite nice approximation. I'm still not sure if it's K-R or Satt., but probably one of its latest modification. I showed the example in my code. It works with lme and gls (which fits the MMRM models - "mixed models without random effects" :) via generalized least square). You can also find it here: https://publicifsv.sund.ku.dk/~jufo/courses/rm2018/nlmePackage.pdf

https://rdrr.io/cran/lavaSearch2/src/R/sCorrect.R

**Comment by strengejacke** [comment]
ok, this issue _should_ be fixed now.
