### ISSUE TITLE
`parameters` function errors with `glmer` models

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#523]
``` r
set.seed(123)
library(lme4)
#> Loading required package: Matrix
# model
mod_glmer <-
  lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    data = ggstatsplot::Titanic_full,
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  )

parameters::parameters(mod_glmer)
#> Error in rbind(deparse.level, ...): numbers of columns of arguments do not match
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2021-05-17 r80314)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2021-06-07                                        
#> 
#> - Packages -------------------------------------------------------------------
#>  package             * version    date       lib
#>  assertthat            0.2.1      2019-03-21 [1]
#>  backports             1.2.1      2020-12-09 [1]
#>  BayesFactor           0.9.12-4.3 2021-06-07 [1]
#>  bayestestR            0.10.5     2021-06-07 [1]
#>  boot                  1.3-28     2021-05-03 [2]
#>  BWStest               0.2.2      2018-10-18 [1]
#>  cachem                1.0.5      2021-05-15 [1]
#>  cli                   2.5.0      2021-04-26 [1]
#>  coda                  0.19-4     2020-09-30 [1]
#>  codetools             0.2-18     2020-11-04 [2]
#>  colorspace            2.0-1      2021-05-04 [1]
#>  correlation           0.6.1      2021-04-09 [1]
#>  crayon                1.4.1      2021-02-08 [1]
#>  DBI                   1.1.1      2021-01-15 [1]
#>  digest                0.6.27     2020-10-24 [1]
#>  dplyr                 1.0.6      2021-05-05 [1]
#>  effectsize            0.4.5      2021-05-25 [1]
#>  ellipsis              0.3.2      2021-04-29 [1]
#>  emmeans               1.6.1      2021-06-01 [1]
#>  estimability          1.3        2018-02-11 [1]
#>  evaluate              0.14       2019-05-28 [1]
#>  fansi                 0.5.0      2021-05-25 [1]
#>  fastmap               1.1.0      2021-01-25 [1]
#>  fs                    1.5.0      2020-07-31 [1]
#>  generics              0.1.0      2020-10-31 [1]
#>  ggplot2               3.3.3      2020-12-30 [1]
#>  ggrepel               0.9.1      2021-01-15 [1]
#>  ggsignif              0.6.1      2021-02-23 [1]
#>  ggstatsplot           0.8.0      2021-06-07 [1]
#>  glue                  1.4.2      2020-08-27 [1]
#>  gmp                   0.6-2      2021-01-07 [1]
#>  gtable                0.3.0      2019-03-25 [1]
#>  gtools                3.8.2      2020-03-31 [1]
#>  highr                 0.9        2021-04-16 [1]
#>  htmltools             0.5.1.1    2021-01-22 [1]
#>  insight               0.14.1     2021-05-28 [1]
#>  ipmisc                6.0.2.9000 2021-06-07 [1]
#>  knitr                 1.33.5     2021-06-07 [1]
#>  kSamples              1.2-9      2019-05-20 [1]
#>  lattice               0.20-44    2021-05-02 [2]
#>  lifecycle             1.0.0      2021-02-15 [1]
#>  lme4                * 1.1-27     2021-05-15 [1]
#>  magrittr              2.0.1      2020-11-17 [1]
#>  MASS                  7.3-54     2021-05-03 [2]
#>  Matrix              * 1.3-3      2021-05-04 [2]
#>  MatrixModels          0.5-0      2021-03-02 [1]
#>  mc2d                  0.1-19     2021-04-18 [1]
#>  memoise               2.0.0      2021-01-26 [1]
#>  minqa                 1.2.4      2014-10-09 [1]
#>  multcomp              1.4-17     2021-04-29 [1]
#>  multcompView          0.1-8      2019-12-19 [1]
#>  munsell               0.5.0      2018-06-12 [1]
#>  mvtnorm               1.1-1      2020-06-09 [1]
#>  nlme                  3.1-152    2021-02-04 [2]
#>  nloptr                1.2.2.2    2020-07-02 [1]
#>  pairwiseComparisons   3.1.6      2021-06-01 [1]
#>  paletteer             1.3.0      2021-01-06 [1]
#>  parameters            0.14.0.1   2021-06-07 [1]
#>  patchwork             1.1.1      2020-12-17 [1]
#>  pbapply               1.4-3      2020-08-18 [1]
#>  performance           0.7.2      2021-05-17 [1]
#>  pillar                1.6.1      2021-05-16 [1]
#>  pkgconfig             2.0.3      2019-09-22 [1]
#>  plyr                  1.8.6      2020-03-03 [1]
#>  PMCMRplus             1.9.0      2021-01-15 [1]
#>  purrr                 0.3.4      2020-04-17 [1]
#>  R6                    2.5.0      2020-10-28 [1]
#>  Rcpp                  1.0.6      2021-01-15 [1]
#>  rematch2              2.1.2      2020-05-01 [1]
#>  reprex                2.0.0      2021-04-02 [1]
#>  reshape               0.8.8      2018-10-23 [1]
#>  rlang                 0.4.11     2021-04-30 [1]
#>  rmarkdown             2.8.6      2021-06-07 [1]
#>  Rmpfr                 0.8-4      2021-04-11 [1]
#>  sandwich              3.0-1      2021-05-18 [1]
#>  scales                1.1.1      2020-05-11 [1]
#>  sessioninfo           1.1.1      2018-11-05 [1]
#>  statsExpressions      1.1.0.9000 2021-06-07 [1]
#>  stringi               1.6.2      2021-05-17 [1]
#>  stringr               1.4.0      2019-02-10 [1]
#>  styler                1.4.1.9003 2021-06-07 [1]
#>  SuppDists             1.1-9.5    2020-01-18 [1]
#>  survival              3.2-11     2021-04-26 [2]
#>  TH.data               1.0-10     2019-01-21 [1]
#>  tibble                3.1.2      2021-05-16 [1]
#>  tidyr                 1.1.3      2021-03-03 [1]
#>  tidyselect            1.1.1      2021-04-30 [1]
#>  utf8                  1.2.1      2021-03-12 [1]
#>  vctrs                 0.3.8      2021-04-29 [1]
#>  withr                 2.4.2      2021-04-18 [1]
#>  WRS2                  1.1-1      2021-02-15 [1]
#>  xfun                  0.23.2     2021-06-07 [1]
#>  xtable                1.8-4      2019-04-21 [1]
#>  yaml                  2.2.1      2020-02-01 [1]
#>  zeallot               0.1.0      2018-01-28 [1]
#>  zoo                   1.8-9      2021-03-09 [1]
#>  source                                    
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  Github (richarddmorey/BayesFactor@4526244)
#>  Github (easystats/bayestestR@f54d688)     
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  local                                     
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  local                                     
#>  Github (yihui/knitr@440d1a6)              
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  Github (easystats/parameters@6fcf8b5)     
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  Github (rstudio/rmarkdown@9dc5d97)        
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  local                                     
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  Github (r-lib/styler@9d376c4)             
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.2.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  Github (yihui/xfun@1416136)               
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#>  CRAN (R 4.1.0)                            
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.2
#> [2] C:/Program Files/R/R-devel/library
```

</details>

Trace:

```r
> traceback()
10: stop("numbers of columns of arguments do not match")
9: rbind(deparse.level, ...)
8: rbind(ran_intercept, ran_slope, ran_corr, ran_sigma)
7: .extract_random_variances_helper(model, ci = ci, effects = effects, 
       component = component, ...)
6: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
       classes)) tryInvokeRestart("muffleWarning"))
5: suppressWarnings(.extract_random_variances_helper(model, ci = ci, 
       effects = effects, component = component, ...))
4: .extract_random_variances.default(model, ci = ci, effects = effects)
3: .extract_random_variances(model, ci = ci, effects = effects)
2: model_parameters.merMod(mod_glmer)
1: parameters::parameters(mod_glmer)
```

**Comment by IndrajeetPatil** [comment]
Works with `sjPlot::tab_model()`:

``` r
set.seed(123)
library(lme4)
#> Loading required package: Matrix
library(sjPlot)

# model
mod_glmer <-
  lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    data = ggstatsplot::Titanic_full,
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  )

tab_model(mod_glmer)
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Survived
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
5.96
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.46 – 24.23
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.013</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Sex \[Male\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.04
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Age \[Child\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
230.26
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.69 – 7921.33
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.003</strong>
</td>
</tr>
<tr>
<td colspan="4" style="font-weight:bold; text-align:left; padding-top:.8em;">
Random Effects
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
3.29
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>Class</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
1.88
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>11</sub> <sub>Class.SexMale</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
1.39
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>11</sub> <sub>Class.AgeChild</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
10.96
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ρ<sub>01</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
-0.92
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.96
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.29
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>Class</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
4
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
2201
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.429 / 0.597
</td>
</tr>
</table>

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Not sure why this is still open, I _think_ I have fixed it already.

**Comment by IndrajeetPatil** [comment]
I am working with the latest GitHub versions of all `easystats` packages and I still the same error.

**Comment by strengejacke** [comment]
ok, then maybe I _wanted_ to fix this ;-)

**Comment by IndrajeetPatil** [comment]
Awesome! Thanks.

``` r
set.seed(123)
library(lme4)
#> Loading required package: Matrix

# model
mod_glmer <-
  lme4::glmer(
    formula = Survived ~ Sex + Age + (Sex + Age | Class),
    data = ggstatsplot::Titanic_full,
    family = stats::binomial(link = "logit"),
    control = lme4::glmerControl(
      optimizer = "Nelder_Mead",
      calc.derivs = FALSE,
      boundary.tol = 1e-7
    )
  )

parameters::parameters(mod_glmer)
#> # Fixed Effects
#> 
#> Parameter   | Log-Odds |   SE |         95% CI |     z |      p
#> ---------------------------------------------------------------
#> (Intercept) |     1.78 | 0.72 | [ 0.38,  3.19] |  2.49 | 0.013 
#> Sex [Male]  |    -3.24 | 0.63 | [-4.48, -2.01] | -5.14 | < .001
#> Age [Child] |     5.44 | 1.81 | [ 1.90,  8.98] |  3.01 | 0.003 
#> 
#> # Random Effects
#> 
#> Parameter                | Coefficient
#> --------------------------------------
#> SD (Intercept: Class)    |        1.37
#> SD (SexMale: Class)      |        1.18
#> SD (AgeChild: Class)     |        3.31
#> Cor (Intercept~SexMale)  |       -0.92
#> Cor (Intercept~AgeChild) |        0.96
#> SD (Residual)            |        1.00
#> 
#> Degrees of freedom based on Wald approximation.
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
Why is there the footer `#> Degrees of freedom based on Wald approximation.`? Got GLMs we don't have error DFs

**Comment by strengejacke** [comment]
> Why is there the footer `#> Degrees of freedom based on Wald approximation.`? Got GLMs we don't have error DFs

Ok, we could just drop the message for models with z-statistic. But doesn't Wald approx. imply infinite DF?

**Comment by mattansb** [comment]
t with DF=inf is the same as Z, but that doesn't mean that every z *has* inf DF.

**Comment by bwiernik** [comment]
Let's make the message, "intervals based on a normal distribution approximation"￼
